# Generated by Django 3.1.14 on 2022-06-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
