# Generated by Django 3.1.14 on 2022-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0003_auto_20220629_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dtls',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course_dtls',
            name='slug',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
