# Generated by Django 3.1.14 on 2022-07-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0004_auto_20220704_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_dtls',
            name='date',
        ),
        migrations.RemoveField(
            model_name='course_dtls',
            name='slug',
        ),
    ]
