# Generated by Django 3.1.14 on 2022-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0005_auto_20220704_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dtls',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
