# Generated by Django 3.1.14 on 2022-07-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0008_payment_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='userCourse',
        ),
    ]
