# Generated by Django 3.1.14 on 2022-07-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0009_auto_20220707_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.course_dtls')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.user_signup')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.course_dtls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.user_signup')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.usercourse')),
            ],
        ),
    ]
