# Generated by Django 3.1.14 on 2022-07-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0012_refcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefCode',
        ),
    ]
