# Generated by Django 3.1.14 on 2022-07-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_point', '0013_delete_refcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial_point.course_dtls')),
            ],
        ),
    ]
